modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    displayURL="https://discord.com/users/1025725101620068373"
    authors="${mod_authors}"
    description='''${mod_description}'''

[[dependencies."${mod_id}"]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="c2me_base"
    mandatory=true
    versionRange="*"
    ordering="NONE"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="c2me_opts_chunkio"
    mandatory=true
    versionRange="*"
    ordering="NONE"
    side="BOTH"